services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=test_user
      - POSTGRES_DB=test_db
